name: ida
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - colorama=0.4.6
  - comm=0.2.3
  - cpython=3.11.13
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - libexpat=2.7.1
  - libffi=3.4.6
  - liblzma=5.8.1
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - openssl=3.5.2
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=25.2
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pywin32=311
  - pyzmq=27.0.1
  - setuptools=80.9.0
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  - wcwidth=0.2.13
  - wheel=0.45.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - pip:
      - acres==0.5.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - alembic==1.16.4
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - argcomplete==3.5.1
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.5
      - bleach==6.2.0
      - blinker==1.9.0
      - borb==2.1.25
      - cachetools==5.5.2
      - category-encoders==2.8.1
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - ci-info==0.3.0
      - click==8.2.0
      - colorlog==6.9.0
      - configobj==5.0.9
      - configparser==7.2.0
      - contourpy==1.3.2
      - cryptography==44.0.3
      - curlify==2.2.1
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - defusedxml==0.7.1
      - distro==1.9.0
      - dotenv==0.9.9
      - dunamai==1.25.0
      - etelemetry==0.3.1
      - fastapi==0.115.12
      - fastjsonschema==2.21.2
      - filelock==3.18.0
      - fire==0.7.1
      - flask==3.1.1
      - fonttools==4.57.0
      - fqdn==1.5.1
      - frozenlist==1.6.0
      - fsspec==2025.9.0
      - git-filter-repo==2.47.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-search-results==2.4.2
      - greenlet==3.2.1
      - h11==0.14.0
      - httpcore==1.0.8
      - httplib2==0.22.0
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface-hub==0.35.3
      - idna==3.10
      - importlib-resources==6.5.2
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jaxtyping==0.3.2
      - jinja2==3.1.6
      - jiter==0.9.0
      - joblib==1.4.2
      - json5==0.12.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.7
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.8
      - langchain==0.3.24
      - langchain-community==0.3.22
      - langchain-core==0.3.68
      - langchain-openai==0.3.14
      - langchain-text-splitters==0.3.8
      - langgraph==0.5.1
      - langgraph-checkpoint==2.1.0
      - langgraph-prebuilt==0.5.2
      - langgraph-sdk==0.1.72
      - langsmith==0.4.4
      - lightgbm==4.6.0
      - looseversion==1.3.0
      - lxml==6.0.0
      - mako==1.3.10
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.10.1
      - mistune==3.1.4
      - mpmath==1.3.0
      - multidict==6.4.3
      - mypy-extensions==1.1.0
      - narwhals==1.39.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.5
      - nibabel==5.3.2
      - nipype==1.10.0
      - notebook==7.4.5
      - notebook-shim==0.2.4
      - numpy==2.2.5
      - openai==1.75.0
      - opencv-python==4.11.0.86
      - optuna==4.4.0
      - orjson==3.10.16
      - ormsgpack==1.10.0
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - pathlib==1.0.1
      - patsy==1.0.1
      - pillow==11.2.1
      - poetry-dynamic-versioning==1.9.1
      - prometheus-client==0.23.1
      - propcache==0.3.1
      - protobuf==6.31.0
      - prov==2.1.1
      - puremagic==1.30
      - pyarrow==20.0.0
      - pybboxes==0.1.6
      - pycparser==2.22
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pydantic-settings==2.9.1
      - pydeck==0.9.1
      - pydot==4.0.1
      - pymupdf==1.26.3
      - pyparsing==3.2.3
      - pypdf2==3.0.1
      - python-barcode==0.15.1
      - python-dotenv==1.1.0
      - python-json-logger==3.3.0
      - pytz==2025.2
      - pywinpty==3.0.0
      - pyxnat==1.6.3
      - pyyaml==6.0.2
      - qrcode==8.2
      - quantile-forest==1.4.0
      - rdflib==7.1.4
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.24.0
      - safetensors==0.6.2
      - sahi==0.11.36
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentence-transformers==5.1.1
      - serpapi==0.1.5
      - shapely==2.1.2
      - simplejson==3.20.1
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - sparqlwrapper==2.0.0
      - sqlalchemy==2.0.40
      - starlette==0.46.2
      - statsmodels==0.14.4
      - streamlit==1.45.1
      - sympy==1.14.0
      - tavily-python==0.7.9
      - tenacity==9.1.2
      - termcolor==3.2.0
      - terminado==0.18.1
      - terminaltables==3.1.10
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - toml==0.10.2
      - tomlkit==0.13.3
      - torch==2.8.0+cu126
      - torch-scatter==2.1.2+pt28cu126
      - torchinfo==1.8.0
      - tqdm==4.67.1
      - traits==7.0.2
      - transformers==4.56.2
      - types-python-dateutil==2.9.0.20250822
      - typing-inspect==0.9.0
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.2.3
      - vastai==0.3.1
      - wadler-lindig==0.1.6
      - watchdog==6.0.0
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - xdg==6.0.0
      - xxhash==3.5.0
      - yarl==1.20.0
      - zstandard==0.23.0
prefix: C:\Users\MTBH\anaconda3\envs\ida
